### ISSUE TITLE
sdsl-lite version 2.1.1=hc9558a2_1001 installs an old compiler

### ISSUE THREAD

**Issue by yp** [conda-forge/sdsl-lite-feedstock#6]
I am trying to install the CXX compiler and the latest version of sdsl-lite (`2.1.1=hc9558a2_1001`) in an environment. However, it only allows to install version gxx version 7.5, which is quite old.
I suspect that this line
https://github.com/conda-forge/sdsl-lite-feedstock/blob/48787208c706f269dfea27a741c8f2a3a0d15e99/recipe/meta.yaml#L25
can be safely removed and that the removal could solve my issue.

**Comment by yp** [comment]
@johnlees @jvolkening Can you have a look?

**Comment by johnlees** [comment]
Yes that seems right – do you want to open a PR with that change and we can review it?
